version: '3.8'
services:
  bestweb_app:
    build: .
    image: bestweb_laravel_app
    container_name: bestweb_app
    volumes:
      - ./:/var/www/html:cached
      - ./vendor:/var/www/html/vendor
    env_file:
      - .env
    depends_on:
      - bestweb_db
    networks:
      - bestweb_network


  bestweb_nginx:
    image: nginx:1.25-alpine
    container_name: bestweb_nginx
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/default.local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - bestweb_app
    networks:
      - bestweb_network


  bestweb_db:
    image: mysql:8.0
    container_name: bestweb_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bestweb
      MYSQL_USER: bestweb
      MYSQL_PASSWORD: password
    ports:
      - "33060:3306"
    volumes:
      - bestweb_db_data:/var/lib/mysql
    networks:
      - bestweb_network


volumes:
  bestweb_db_data:


networks:
  bestweb_network:
    driver: bridge